import { useEffect, useState } from 'react';
import Head from 'next/head'
import CountryCard from '../components/CountryCard';
import SearchInput from '../components/SearchInput';
import SelectFilter from '../components/SelectFilter';
import Link from 'next/link';

export default function Home({ data }) {

  const [query, setQuery] = useState('')
  const [filteredData, setFilteredData] = useState(data)

  const  searchCountry = (e) => {
    setQuery(e.target.value)
    const filtered = data.filter(country => country.name.common.toLowerCase().includes(e.target.value.toLowerCase()))
    setFilteredData([...filtered])
  }

  const handleSelect = (e) => {
    console.log(e.target.value)
    if (e.target.value === 'az') {
      const filtered = data.sort((a, b) => a.name.common.localeCompare(b.name.common))
      setFilteredData([...filtered])
    }
    if (e.target.value === 'all') {
      setFilteredData(data)
    }
    if (e.target.value === 'population') { 
      const filtered = data.sort((a, b) => b.population - a.population)
      setFilteredData([...filtered])
    }
    if (e.target.value === 'africa') { 
      const filtered = data.filter(country => country.region === 'Africa')
      setFilteredData([...filtered])
    }
    if (e.target.value === 'asia') {
      const filtered = data.filter(country => country.region === 'Asia')
      setFilteredData([...filtered])
    }
    if (e.target.value === 'europe') { 
      const filtered = data.filter(country => country.region === 'Europe')
      setFilteredData([...filtered])
    }
    if (e.target.value === 'americas') {
      const filtered = data.filter(country => country.region === 'Americas')
      setFilteredData([...filtered])
    }
    if (e.target.value === 'oceania') {
      const filtered = data.filter(country => country.region === 'Oceania')
      setFilteredData([...filtered])
    }
  }

  useEffect(() => { }, [filteredData])

 
  return (
    <>
      <Head>
        <title>Countries v3 - NextJS - TailwindCSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky w-full top-0 bg-white z-10 py-5 shadow-lg mb-5">
        <div className="container mx-auto px-5">
          <h1 className='text-3xl font-bold mb-5'>Countries</h1>
          <div className="flex justify-between mb-5 gap-20">
            <SearchInput query={query} searchCountry={searchCountry} />
            <SelectFilter handleSelect={handleSelect} />
          </div>
        </div>
      </div>
      <div className='container mx-auto mb-5 px-5'>
        <div className='mb-5 text-center'>
          <span className="font-bold">{filteredData.length}</span> / <span className="font-medium">{data.length}</span>
        </div>
        {
          filteredData.length > 0 ? (
            <div className='grid grid-cols-1 lg:grid-cols-4 gap-4 md:grid-cols-2'>
              {filteredData.map(country => (
                <Link href={`/detail/${country.cca3?.toLowerCase()}`} key={country.name.common}>
                  <a>
                    <CountryCard country={country} />
                  </a>
                </Link>
              ))}
            </div>
          ) : (
              <div className='text-center'>
                <h2 className='text-xl font-bold'>No Countries Found</h2>
              </div>
          )
        }
      </div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://restcountries.com/v3.1/all')
  const data = await res.json()
  return {
    props: {
      data,
    },
  }
}
